[package]
name = "git-lumina"
version = "1.0.0"
edition = "2024"
description = "A TUI Git client to visualize and manage your Git repositories efficiently."
authors = ["Helene N."]
keywords = ["git", "tui", "terminal", "client", "repository", "visualization"]
license = "MIT"
repository = "https://github.com/helene-nguyen/rust-git-lumina.git"

[[bin]]
name = "lumina"
path = "src/main.rs"

[[bin]]
name = "gitlumina"
path = "src/main.rs"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
git2 = "0.19"
anyhow = "1.0"
chrono = "0.4"